Volt, overriding callMacro renders error
Extending Volt class and overriding callMacro($name, $arguments) renders errors due to signature mismatch:
ErrorException: Declaration of Pow\Mvc\Volt::callMacro() should be compatible with Phalcon\Mvc\View\Engine\Volt::callMacro($name, array $arguments)

Method signature should probably typehint $arguments as array